drop SEQUENCE IF EXISTS iot_air_q_sd_seq;
drop SEQUENCE IF EXISTS iot_air_q_sni_seq;
drop table if exists iot_air_q_sensor_data;
drop table if exists iot_air_q_sensor_node_config;

CREATE SEQUENCE IF NOT EXISTS iot_air_q_sd_seq;
CREATE SEQUENCE IF NOT EXISTS iot_air_q_sni_seq;

CREATE TABLE IF NOT EXISTS iot_air_q_sensor_data
(
    id int8 not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 cycle),
    mac_address text not null,
    package_id uuid not null,
    sensor_name text not null,
    reading_type text not null,
    reading_data decimal not null,
    created timestamp not null,
    constraint iaq_sd_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS iot_air_q_sensor_node_config
(
    id int8 not null generated by default as identity ( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 cycle),
    ip text not null,
    mac_address text not null,
    created timestamp not null,
    last_modified timestamp null,
    constraint iaq_sni_pkey primary key (id)
);
